import type { Beat } from "./beats.js";

/**
 * Seed catalog — the 20 warm beats mirrored exactly from the live v0.1
 * deployment at https://openbeat.vercel.app/v1/catalog (September 2026).
 * Concept URIs are in newsapi.ai's Wikipedia dialect, so these entries are
 * directly queryable against the provider once ingestion lands (Phase 1).
 */
export const SEED_BEATS: readonly Beat[] = [
  {
    beat_id: "b_e857ee04eb3f",
    label: "African Continental Free Trade Area",
    concept_uris: ["http://en.wikipedia.org/wiki/African_Continental_Free_Trade_Area"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Unrelated trade agreements",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_1617e42f6719",
    label: "Antarctic Treaty",
    concept_uris: ["http://en.wikipedia.org/wiki/Antarctic_Treaty_System"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Travel promotions",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_5a923cd16401",
    label: "Baltic shipping",
    concept_uris: ["http://en.wikipedia.org/wiki/Baltic_Sea"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Unrelated coastal tourism",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_c63577b47252",
    label: "Brazil deforestation",
    concept_uris: ["http://en.wikipedia.org/wiki/Deforestation_in_Brazil"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Unrelated agriculture",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_c962a5ed6235",
    label: "Croatia energy",
    concept_uris: ["http://en.wikipedia.org/wiki/Energy_in_Croatia"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Unrelated tourism",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_4a0bab7a98f9",
    label: "ECB monetary policy",
    concept_uris: ["http://en.wikipedia.org/wiki/European_Central_Bank"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Commercial bank marketing",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_dab9c000dca5",
    label: "EU AI Act",
    concept_uris: ["http://en.wikipedia.org/wiki/Artificial_Intelligence_Act"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Consumer AI launches",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_313ff0d2b260",
    label: "EU competition policy",
    concept_uris: ["http://en.wikipedia.org/wiki/European_Union_competition_law"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Consumer complaints",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_8ebb0cdad936",
    label: "European battery regulation",
    concept_uris: ["http://en.wikipedia.org/wiki/Battery_regulation"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Consumer product reviews",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_191edd8895e2",
    label: "Federal Reserve",
    concept_uris: ["http://en.wikipedia.org/wiki/Federal_Reserve"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Personal finance tips",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_df0f40df7410",
    label: "Iceland volcanoes",
    concept_uris: ["http://en.wikipedia.org/wiki/Volcanism_of_Iceland"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Volcanoes outside Iceland",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_7158f5fde7c7",
    label: "Japan earthquakes",
    concept_uris: ["http://en.wikipedia.org/wiki/Earthquakes_in_Japan"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Earthquakes outside Japan",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_bb964843350e",
    label: "NVIDIA",
    concept_uris: ["http://en.wikipedia.org/wiki/Nvidia"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Unrelated gaming reviews",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_06dabc7c4339",
    label: "Quantum error correction",
    concept_uris: ["http://en.wikipedia.org/wiki/Quantum_error_correction"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Unrelated quantum product promotion",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_b23abb40a2af",
    label: "Space launch activity",
    concept_uris: ["http://en.wikipedia.org/wiki/Space_launch"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Science fiction",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_78de9ccc21a4",
    label: "Strait of Hormuz",
    concept_uris: ["http://en.wikipedia.org/wiki/Strait_of_Hormuz"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "General Middle East news",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_4d1c99160af5",
    label: "Swiss monetary policy",
    concept_uris: ["http://en.wikipedia.org/wiki/Swiss_National_Bank"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Retail investing tips",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_223175e1243e",
    label: "Taiwan semiconductors",
    concept_uris: ["http://en.wikipedia.org/wiki/Semiconductor_industry_in_Taiwan"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "General electronics reviews",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_bb89135021c5",
    label: "US–China export controls",
    concept_uris: ["http://en.wikipedia.org/wiki/Export_control"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "Unrelated trade commentary",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
  {
    beat_id: "b_6379352c6ac7",
    label: "WHO disease outbreaks",
    concept_uris: ["http://en.wikipedia.org/wiki/Disease_outbreak"],
    topic_filters: [],
    languages: ["eng"],
    excludes: "General wellness",
    state: "warm",
    refresh_interval_minutes: 60,
    freshness_slo_minutes: 90,
  },
];
