-- NewsGraph schema.
--
-- The whole thing: three tables and one function. Apply to any empty Postgres:
--
--   npm run db:setup          # uses DATABASE_URL
--
-- Idempotent, so it is safe to re-run.

create table if not exists public.news_articles (
  id                bigint generated by default as identity primary key,
  beat_id           text        not null,
  provider_uri      text        not null,
  title             text        not null,
  excerpt           text        not null,
  url               text        not null,
  source            text        not null,
  published_at      timestamptz not null,
  first_indexed_at  timestamptz not null default now()
);

-- One row per topic: what the API reports as freshness. Without a row a topic
-- is `unavailable`, which is the honest default before its first ingestion.
create table if not exists public.news_ingestion_status (
  beat_id             text primary key,
  last_checked_at     timestamptz,
  last_success_at     timestamptz,
  last_error          text,
  last_article_count  integer not null default 0
);

-- Only a hash is stored. The plaintext worker credential lives in the
-- environment, never in the database.
create table if not exists public.news_worker_keys (
  token_hash text primary key
);

-- Deduplication is per topic on the publisher URL. The provider returns the
-- same story repeatedly across windows, so this is what makes a repeat run a
-- no-op rather than a duplicate.
create unique index if not exists news_articles_beat_id_url_key
  on public.news_articles (beat_id, url);

-- The read path: newest-first within a topic, and the cursor walk uses
-- (beat_id, id) for its boundary comparison.
create index if not exists news_articles_beat_id_idx
  on public.news_articles (beat_id, id);

create index if not exists news_articles_published_idx
  on public.news_articles (published_at);

-- The catalog reports a per-topic count and a count inside a time window. The
-- (beat_id, id) index cannot serve that; without this the counts query scans
-- every article and took ~1.9s at 30k rows, which the dashboard felt.
create index if not exists news_articles_beat_published_idx
  on public.news_articles (beat_id, published_at desc);

-- ── append_news_articles ────────────────────────────────────────────────
-- One atomic write per topic: insert the batch, then stamp freshness. Doing
-- both here is what keeps `last_success_at` from ever disagreeing with what is
-- actually stored.
--
-- The advisory lock serialises concurrent runs for the same project. The batch
-- is bounded so a malformed provider response cannot become an unbounded write.
-- The 30-day floor and 5-minute ceiling are the depth window and a guard
-- against a provider timestamped in the future.
create or replace function public.append_news_articles(p_beat_id text, p_articles jsonb)
returns integer
language plpgsql
set search_path to ''
as $function$
declare inserted_count integer;
begin
  perform pg_advisory_xact_lock(762341987);
  if jsonb_typeof(p_articles) <> 'array' or jsonb_array_length(p_articles) > 1000 then
    raise exception 'Invalid article batch';
  end if;
  insert into public.news_articles(beat_id, provider_uri, title, excerpt, url, source, published_at)
  select p_beat_id,
         item->>'provider_uri',
         left(item->>'title', 240),
         left(coalesce(item->>'excerpt', ''), 320),
         item->>'url',
         left(item->>'source', 120),
         (item->>'published_at')::timestamptz
  from jsonb_array_elements(p_articles) item
  where (item->>'published_at')::timestamptz >= now() - interval '30 days'
    and (item->>'published_at')::timestamptz <= now() + interval '5 minutes'
  on conflict (beat_id, url) do nothing;
  get diagnostics inserted_count = row_count;

  insert into public.news_ingestion_status(beat_id, last_checked_at, last_success_at, last_error, last_article_count)
  values (p_beat_id, now(), now(), null, inserted_count)
  on conflict (beat_id) do update set
    last_checked_at = excluded.last_checked_at,
    last_success_at = excluded.last_success_at,
    last_error = null,
    last_article_count = excluded.last_article_count;

  return inserted_count;
end;
$function$;

-- ── Keys and rate limiting ──────────────────────────────────────────────
-- Keys are optional. Anonymous callers are limited by address; a key raises
-- the ceiling. Nothing in the public contract changes, which matters because
-- every surface of this project documents the API as needing no credential.

create table if not exists public.api_keys (
  key_hash      text primary key,          -- sha-256 of the secret, never the secret
  label         text not null default '',
  created_at    timestamptz not null default now(),
  last_used_at  timestamptz,
  revoked_at    timestamptz
);

-- A fixed-window counter. One row per bucket per minute, incremented in a
-- single statement so two concurrent requests cannot both read a stale count.
create table if not exists public.api_usage (
  bucket        text not null,             -- 'key:<hash>' or 'ip:<hash>'
  window_start  timestamptz not null,
  count         integer not null default 0,
  primary key (bucket, window_start)
);

-- For the sweep that drops expired windows.
create index if not exists api_usage_window_idx on public.api_usage (window_start);
