-- Pleiades 0003 — seed the warm beat catalog + enable Realtime for packs
-- Mirrors the canonical seed in packages/contracts/src/seed.ts (20 beats).
-- Idempotent: re-running never duplicates rows.

insert into beats (beat_id, label, concept_uris, languages, excludes) values
  ('b_e857ee04eb3f', 'African Continental Free Trade Area',
    array['http://en.wikipedia.org/wiki/African_Continental_Free_Trade_Area'],
    array['eng','fra'], 'Unrelated trade agreements'),
  ('b_1617e42f6719', 'Antarctic Treaty',
    array['http://en.wikipedia.org/wiki/Antarctic_Treaty_System'],
    array['eng'], 'Travel promotions'),
  ('b_5a923cd16401', 'Baltic shipping',
    array['http://en.wikipedia.org/wiki/Baltic_Sea'],
    array['eng'], 'Unrelated coastal tourism'),
  ('b_c63577b47252', 'Brazil deforestation',
    array['http://en.wikipedia.org/wiki/Deforestation_in_Brazil'],
    array['por','eng'], 'Unrelated agriculture'),
  ('b_c962a5ed6235', 'Croatia energy',
    array['http://en.wikipedia.org/wiki/Energy_in_Croatia'],
    array['hrv','eng'], 'Unrelated tourism'),
  ('b_4a0bab7a98f9', 'ECB monetary policy',
    array['http://en.wikipedia.org/wiki/European_Central_Bank'],
    array['eng','deu'], 'Commercial bank marketing'),
  ('b_dab9c000dca5', 'EU AI Act',
    array['http://en.wikipedia.org/wiki/Artificial_Intelligence_Act'],
    array['eng','deu'], 'Consumer AI launches'),
  ('b_313ff0d2b260', 'EU competition policy',
    array['http://en.wikipedia.org/wiki/European_Union_competition_law'],
    array['eng','fra'], 'Consumer complaints'),
  ('b_8ebb0cdad936', 'European battery regulation',
    array['http://en.wikipedia.org/wiki/Battery_regulation'],
    array['eng','deu'], 'Consumer product reviews'),
  ('b_191edd8895e2', 'Federal Reserve',
    array['http://en.wikipedia.org/wiki/Federal_Reserve'],
    array['eng'], 'Personal finance tips'),
  ('b_df0f40df7410', 'Iceland volcanoes',
    array['http://en.wikipedia.org/wiki/Volcanism_of_Iceland'],
    array['eng','isl'], 'Volcanoes outside Iceland'),
  ('b_7158f5fde7c7', 'Japan earthquakes',
    array['http://en.wikipedia.org/wiki/Earthquakes_in_Japan'],
    array['jpn','eng'], 'Earthquakes outside Japan'),
  ('b_bb964843350e', 'NVIDIA',
    array['http://en.wikipedia.org/wiki/Nvidia'],
    array['eng'], 'Unrelated gaming reviews'),
  ('b_06dabc7c4339', 'Quantum error correction',
    array['http://en.wikipedia.org/wiki/Quantum_error_correction'],
    array['eng'], 'Unrelated quantum product promotion'),
  ('b_b23abb40a2af', 'Space launch activity',
    array['http://en.wikipedia.org/wiki/Space_launch'],
    array['eng'], 'Science fiction'),
  ('b_78de9ccc21a4', 'Strait of Hormuz',
    array['http://en.wikipedia.org/wiki/Strait_of_Hormuz'],
    array['eng','ara'], 'General Middle East news'),
  ('b_4d1c99160af5', 'Swiss monetary policy',
    array['http://en.wikipedia.org/wiki/Swiss_National_Bank'],
    array['deu','eng'], 'Retail investing tips'),
  ('b_223175e1243e', 'Taiwan semiconductors',
    array['http://en.wikipedia.org/wiki/Semiconductor_industry_in_Taiwan'],
    array['eng','zho'], 'General electronics reviews'),
  ('b_bb89135021c5', 'US–China export controls',
    array['http://en.wikipedia.org/wiki/Export_control'],
    array['eng','zho'], 'Unrelated trade commentary'),
  ('b_6379352c6ac7', 'WHO disease outbreaks',
    array['http://en.wikipedia.org/wiki/Disease_outbreak'],
    array['eng','fra'], 'General wellness')
on conflict (beat_id) do nothing;

-- Phase 2 readiness: broadcast pack inserts over Supabase Realtime.
alter publication supabase_realtime add table packs;
